// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using RESTAPI.Models;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace RESTAPI.Data
{
    public partial interface IBOOKDATABASEContextProcedures
    {
        Task<int> CreateBookAsync(string Title, string Isbn, string PublisherName, string AuthorName, string CategoryName, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> DeleteBookAsync(int? BookId, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<GetAllBookResult>> GetAllBookAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<GetBookByIdResult>> GetBookByIdAsync(int? BookId, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> UpdateBookAsync(int? BookId, string Title, string ISBN, string PublisherName, string AuthorName, string CategoryName, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
